# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kapela Cmaj7
email:
description: >- # this means to ignore newlines until "baseurl:"
  Jsme mladá studentská kapela složená z party kamarádů, které hudba prostě baví. 
  Repertoár máme od každého žánru trochu, od big beatu, po rock, pop, funk a 
  uslyšíte české i zahraniční hity, které osloví nejširší publikum. 
  Zahrajeme vám rádi při každé příležitosti. Na plese, svatbě, oslavě a jakékoli jiné události. 
  A proč si pro Vaši akci vybrat zrovna nás?
  Myslíme si, že dokážeme zajistit kvalitní živou produkci a vneseme do vašeho večera pohodovou taneční atmosféru.
facebook_username: Kapela Cmaj7
instagram_username: _cmaj7__
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: CZ # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kapela Cmaj7"
  avatar : "/assets/images/logo_cmaj7.png"
  bio    : "Mladá kapela s hudbou pro každou příležitost."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kapela-cmaj7.cz/"
    - label: "Facebook"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://www.facebook.com/kapelacmaj7"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/_cmaj7__/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kapela-cmaj7.cz/"
    - label: "Facebook"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://www.facebook.com/kapelacmaj7"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/_cmaj7__/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
